### ISSUE TITLE
Implement Queue.dropping

### ISSUE THREAD

**Issue by wi101** [scalaz/scalaz-ioqueue#15]
Using `Queue.dropping` the behavior of Queue will be changed when is full.
It drops the new elements when the Queue is full.

**Comment by randbw** [comment]
I'll give this a go 😃

**Comment by LGLO** [comment]
Will `.dropping` change type of `Queue` to some type having API that would signal if element was dropped, like `offerXXX(a: A): IO[Nothing, Boolean]`?

I think it's good for a user to have this information.
Please consider a HTTP POST endpoint that enqueues input data. In case queue is full we would like to return 5xx instead of 204.
